In [1]:
import sys
import random
import torch
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader, Dataset
import sumolib
import traci
from sumolib import checkBinary
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.data import Data
import sys
import io
from contextlib import redirect_stdout
import matplotlib.pyplot as plt
import pandas as pd
import os
import math
from utils import *


if 'SUMO_HOME' in os.environ:
    print('SUMO_HOME found')
    sys.path.append(os.path.join(os.environ['SUMO_HOME'], 'tools'))

# sumoBinary = checkBinary('sumo-gui')
sumoBinary = checkBinary('sumo')
roadNetwork = "./config/osm.sumocfg"
sumoCmd = [sumoBinary, "-c", roadNetwork, "--start", "--quit-on-end"]
# use gpu if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device: " + str(device))

SUMO_HOME found
SUMO_HOME found
Using device: cuda


In [2]:
planned_path = get_planned_path()
checkpoints = list(planned_path.values())
checkpoints = torch.tensor(checkpoints).float() / 10

 Retrying in 1 seconds
***Starting server on port 59101 ***
Loading net-file from './config/osm.net.xml.gz' ... done (157ms).
Loading additional-files from './config/osm.poly.xml.gz' ... done (104ms).
Loading done.
Simulation version 1.20.0 started with time: 0.00.
Simulation ended at time: 10431.00
Reason: TraCI requested termination.
Performance: 
 Duration: 12.09s
 TraCI-Duration: 8.04s
 Real time factor: 863.065
 UPS: 92862.651001
Vehicles: 
 Inserted: 3937
 Running: 0
 Waiting: 0
Statistics (avg of 3937):
 RouteLength: 3678.32
 Speed: 12.97
 Duration: 285.07
 WaitingTime: 12.59
 TimeLoss: 59.04
 DepartDelay: 0.59



In [3]:
def project_to_nearest(prediction, planned_path):
    with torch.no_grad():
        starts = planned_path[:, :-1, :]
        to = planned_path[:, 1:, :]

        prediction = prediction.unsqueeze(1).repeat(1, starts.shape[1], 1)
        ap = prediction - starts
        ab = to - starts
        numerator = torch.einsum('ijk,ijk->ij', ap, ab)
        denominator = torch.einsum('ijk,ijk->ij', ab, ab)
        t = numerator / denominator
        t = torch.nan_to_num(t, nan=0.0)
        t = torch.clamp(t, 0, 1)
        projections = starts + t.unsqueeze(2) * ab
        diff = projections - prediction
        distances = torch.norm(diff, dim=2)
        min_indices = torch.argmin(distances, dim=1)
        projections = projections[range(projections.shape[0]), min_indices]
        return projections, min_indices


def project_to_nearest_with_checkpoints(prediction, planned_path):
    with torch.no_grad():
        starts = planned_path[:, :-1, :]
        to = planned_path[:, 1:, :]

        prediction = prediction.unsqueeze(1).repeat(1, starts.shape[1], 1)
        ap = prediction - starts
        ab = to - starts
        numerator = torch.einsum('ijk,ijk->ij', ap, ab)
        denominator = torch.einsum('ijk,ijk->ij', ab, ab)
        t = numerator / denominator
        t = torch.nan_to_num(t, nan=0.0)
        t = torch.clamp(t, 0, 1)
        projections = starts + t.unsqueeze(2) * ab
        diff = projections - prediction
        distances = torch.norm(diff, dim=2)
        min_indices = torch.argmin(distances, dim=1)
        projections = projections[range(projections.shape[0]), min_indices]
        next_checkpoint = to[range(to.shape[0]), min_indices]
        pad_to = F.pad(to, (0, 0, 1, 0), value=0)
        next_next_checkpoint = pad_to[range(to.shape[0]), min_indices + 1]
        projections_with_checkpoints = torch.cat((projections, next_checkpoint, next_next_checkpoint), dim=1)
        return projections_with_checkpoints

In [4]:
# Example DataFrame loading
df = pd.read_csv('rovaniemi_trajectories.csv')
num_cols = df.shape[1]
position_indices = [i for i in range(num_cols) if i % 4 == 1 or i % 4 == 2]
position_df = df.iloc[:, position_indices]
position_array = position_df.to_numpy()
sequence_length = len(position_indices) // 2
tensor_list = []

for row in position_array:
    reshaped_tensor = torch.tensor(row.reshape(sequence_length, 2))
    tensor_list.append(reshaped_tensor)

all_trajectories_tensor = torch.stack(tensor_list).float() / 10

next_checkpoint = torch.zeros_like(all_trajectories_tensor)
next_next_checkpoint = torch.zeros_like(all_trajectories_tensor)
checkpoints_pad_1 = F.pad(checkpoints, (0, 0, 1, 0))
for i in range(all_trajectories_tensor.shape[1]):
    _, min_indices = project_to_nearest(all_trajectories_tensor[:, i], checkpoints)
    next_checkpoint[:, i] = checkpoints_pad_1[range(checkpoints.shape[0]), min_indices+1]
    next_next_checkpoint[:, i] = checkpoints_pad_1[range(checkpoints.shape[0]), min_indices+2]

all_trajectories_tensor = torch.cat((all_trajectories_tensor, next_checkpoint, next_next_checkpoint), dim=2)

In [5]:
# break trajectories into 1000 by 1000 cells
trajectory_list = []
checkpoints_list = []
for i in range(all_trajectories_tensor.shape[0]):
    trajectory = all_trajectories_tensor[i]
    path = checkpoints[i]
    modif = ((trajectory[0, :2] // 100) * 100 - 10).repeat(1, 3)
    trajectory_to_add = []
    next_trajectory_to_add = []
    for j in range(trajectory.shape[0]):
        if trajectory[j:, :2].max() == 0:
            break
        trajectory_j = (trajectory[j] - modif).squeeze()
        # if the vehicle move out of the current cell
        if trajectory_j[0] < 0 or trajectory_j[1] < 0 or trajectory_j[0] > 120 or trajectory_j[1] > 120:
            # we first add all the points in the current cell
            trajectory_list.append(torch.stack(trajectory_to_add))
            # then we add checkpoints
            checkpoints_list.append(path-modif.squeeze()[:2])

            # we reset the to add list
            trajectory_to_add = []
            modif = ((trajectory[j, :2] // 100) * 100 - 10).repeat(1, 3)
            # reset the to_add list, adding a part of the history to the new trajectory
            if j != trajectory.shape[0] - 1:
                rewind = 0
                while True:
                    trajectory_k = (trajectory[j - rewind] - modif).squeeze()
                    if trajectory_k[0] < 0 or trajectory_k[0] > 120 or trajectory_k[1] < 0 or trajectory_k[1] > 120:
                        rewind += 1
                    else:
                        break
                trajectory_to_add = trajectory_to_add[:-rewind]

        else:
            trajectory_to_add.append(trajectory_j)


In [6]:
checkpoints = torch.stack(checkpoints_list)
def pad_tensors(tensors):
    max_length = max([t.shape[0] for t in tensors])
    padded_tensors = []
    for tensor in tensors:
        padded_tensor = F.pad(tensor, (0, 0, 0, max_length - tensor.shape[0]))
        padded_tensors.append(padded_tensor)
    return torch.stack(padded_tensors)

all_trajectories_tensor = pad_tensors(trajectory_list)

In [7]:
def missing(x, y, z, p):
    return torch.tensor(np.repeat(np.random.rand(x * y) < p, z).reshape(x, y, z)).float()

def generate_masks(tensors, min_mask_ratio=0.0, max_mask_ratio=0.1, missing_ratio=0.6, complete_traj_ratio=0.75):
    initial_masks = missing(tensors.shape[0], tensors.shape[1], tensors.shape[2], missing_ratio)
    masks = []
    for initial_mask in initial_masks:
        if np.random.rand() < complete_traj_ratio:
            masks.append(torch.zeros_like(initial_mask).tolist())
            continue
        seq_length = initial_mask.shape[0]
        mask_start = np.random.randint(int(seq_length * min_mask_ratio), int(seq_length * max_mask_ratio))
        mask = torch.zeros_like(initial_mask)
        mask[:, :mask_start] = 1
        mask = initial_mask * mask
        mask[0] = 0
        mask[1] = 0
        masks.append(mask.tolist())
    return torch.tensor(masks)

# split the data into training and validation sets
# because the data is randomly generated, we don't need to shuffle it
train_ratio = 0.8
train_size = int(train_ratio * all_trajectories_tensor.shape[0])
train_trajectories_tensor = all_trajectories_tensor[:train_size]
val_trajectories_tensor = all_trajectories_tensor[train_size:]

train_checkpoints = checkpoints[:train_size]
val_checkpoints = checkpoints[train_size:]

train_mask = generate_masks(train_trajectories_tensor)

class DatasetWithPlans(Dataset):
    def __init__(self, tensor, input_mask, checkpoints):
        self.tensor = tensor.float().to(device)
        self.input_mask = input_mask.float().to(device)
        self.checkpoints = checkpoints.float().to(device)
    def __len__(self):
        return len(self.tensor)
    def __getitem__(self, idx):
        return self.tensor[idx], self.input_mask[idx], self.checkpoints[idx]
    
train_dataset = DatasetWithPlans(train_trajectories_tensor, train_mask, train_checkpoints)

In [8]:
class GRUModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(GRUModel, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.gru = nn.GRU(input_size, hidden_size, num_layers, batch_first=True)
        self.fc1 = nn.Linear(hidden_size, int(hidden_size/2))
        self.fc2 = nn.Linear(int(hidden_size/2), num_classes)
        self.relu = nn.ReLU()
    
    def forward(self, x, h0=None):
        if h0 is None:
            h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        out, hidden = self.gru(x, h0)  
        out = self.fc1(out[:, -1, :])
        out = self.relu(out)
        out = self.fc2(out)
        return out, hidden

class CustomMSE(nn.Module):
    def __init__(self):
        super(CustomMSE, self).__init__()

    def forward(self, output, target):
        # where target is 0
        mask = (target != 0).float().to(device)
        mse = torch.mean(((output - target) ** 2) * mask)
        directional_diff = torch.mean(torch.abs(torch.atan2(output[:, 1], output[:, 0]) - torch.atan2(target[:, 1], target[:, 0])))
        return mse + directional_diff

In [12]:
def train_model(model, dataloader, epochs, optimizer, criterion):
    model.train()
    for epoch in range(epochs):
        total_loss = 0
        for inputs, masks, planned_path in dataloader:
            optimizer.zero_grad()
            hidden = None
            loss = 0
            # Autoregressive prediction
            # Start with the first input and predict each subsequent step
            seq_len = inputs.size(1)
            current_input = inputs[:, 0, :].unsqueeze(1)
            for t in range(1, seq_len):
                prediction, hidden = model(current_input, hidden)

                previous_input = inputs[:, t-1, :2]
                if epoch > 8:
                    projection_with_checkpoints = project_to_nearest_with_checkpoints(prediction, planned_path)
                    current_input = (projection_with_checkpoints * masks[:, t, :] + inputs[:, t, :] * (1-masks[:, t, :])).unsqueeze(1)
                else:
                    current_input = inputs[:, t, :].unsqueeze(1)
                if t > 1:
                    loss += criterion(prediction - previous_input, inputs[:, t, :2]-previous_input) #(current_input-previous_input).squeeze(1))
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
 
        print(f'Epoch {epoch+1}, Loss: {total_loss / len(dataloader)}')
        # if epoch >= 20 and total_loss / len(dataloader) < 2000:
        #     break

train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True)

model = GRUModel(input_size=6, hidden_size=256, num_layers=2, num_classes=2).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = CustomMSE()
train_model(model, train_dataloader, 20, optimizer, criterion)

Epoch 1, Loss: 91378.32451235702
Epoch 2, Loss: 7747.486316955167
Epoch 3, Loss: 4553.354701222937
Epoch 4, Loss: 4321.49547302645
Epoch 5, Loss: 4105.543350119996
Epoch 6, Loss: 3699.558285781761
Epoch 7, Loss: 3527.3259468826595
Epoch 8, Loss: 3627.388153275633
Epoch 9, Loss: 3330.6210889629288
Epoch 10, Loss: 5547.016051049326
Epoch 11, Loss: 3955.472239774816
Epoch 12, Loss: 3770.2608778211807
Epoch 13, Loss: 4137.996933083129
Epoch 14, Loss: 4095.3952030356413
Epoch 15, Loss: 3854.801416334763
Epoch 16, Loss: 4000.2583901399103
Epoch 17, Loss: 3708.1426674836603
Epoch 18, Loss: 3553.5977703418607
Epoch 19, Loss: 3446.2509175219566
Epoch 20, Loss: 3261.9979431551264


In [13]:
def checkModel(model, inputs, masks, paths):
    model.eval()
    with torch.no_grad():
        hidden = None
        seq_len = inputs.size(1)
        current_input = inputs[:, 0, :].unsqueeze(1)
        for t in range(1, seq_len):
            prediction, hidden = model(current_input, hidden)
            projection_with_checkpoints = project_to_nearest_with_checkpoints(prediction, paths)
            current_input = (projection_with_checkpoints * masks[:, t, :] + inputs[:, t, :] * (1-masks[:, t, :])).unsqueeze(1)
            print(projection_with_checkpoints[0][:2]*10, inputs[:, t, :][0][:2]*10)

# get the first batch in dataloader
val_mask = generate_masks(val_trajectories_tensor, missing_ratio=0.5, complete_traj_ratio=0)
val_dataset = DatasetWithPlans(val_trajectories_tensor, val_mask, val_checkpoints)
val_dataloader = DataLoader(val_dataset, batch_size=64, shuffle=True)
inputs, masks, paths = next(iter(val_dataloader))

checkModel(model, inputs, masks, paths)

tensor([-15.4651, 189.8609], device='cuda:0') tensor([253.0347, 157.6392], device='cuda:0')
tensor([278.4694, 153.8990], device='cuda:0') tensor([278.3868, 153.9111], device='cuda:0')
tensor([299.9497, 150.7313], device='cuda:0') tensor([302.5504, 150.3306], device='cuda:0')
tensor([304.4930, 150.0313], device='cuda:0') tensor([327.2165, 146.5476], device='cuda:0')
tensor([304.5288, 150.0258], device='cuda:0') tensor([352.4036, 142.6964], device='cuda:0')
tensor([350.8958, 142.9269], device='cuda:0') tensor([375.8731, 139.1299], device='cuda:0')
tensor([348.6491, 143.2704], device='cuda:0') tensor([399.6039, 135.6370], device='cuda:0')
tensor([411.4608, 133.8916], device='cuda:0') tensor([424.9741, 131.9026], device='cuda:0')
tensor([435.9323, 130.2896], device='cuda:0') tensor([448.8678, 128.3856], device='cuda:0')
tensor([436.3769, 130.2242], device='cuda:0') tensor([473.7274, 124.7298], device='cuda:0')
tensor([438.5770, 129.9003], device='cuda:0') tensor([497.7267, 121.2016], devic

In [14]:
def evaluate_model(model, dataloader):
    model.eval()
    total_loss = 0
    steps = 0
    for inputs, masks, paths in dataloader:
        hidden = None
        loss = 0
        seq_len = inputs.size(1)
        current_input = inputs[:, 0, :].unsqueeze(1)
        for t in range(1, seq_len):
            new_steps = int(sum((inputs[:, t, :2].reshape(-1) != 0).float().to(device))) / 2
            if new_steps == 0:
                break
            steps += new_steps
            prediction, hidden = model(current_input, hidden)
            projection_with_checkpoints = project_to_nearest_with_checkpoints(prediction, paths)
            current_input = (projection_with_checkpoints * masks[:, t, :] + inputs[:, t, :] * (1-masks[:, t, :])).unsqueeze(1)
            loss += torch.norm((projection_with_checkpoints[:, :2] - inputs[:, t, :2]) * 10, dim=1) * (inputs[:, t, :2] != 0)[:, 0]
        total_loss += loss.sum().item()
    print(f'Validation Loss: {total_loss / steps}')

# load model
# model = GRUModel(input_size=6, hidden_size=256, num_layers=2, num_classes=2).to(device)
# model.load_state_dict(torch.load('gru_model.pth'))
for i in [0.9, 0.8, 0.7, 0.6, 0.5, 0]:
    val_mask = generate_masks(val_trajectories_tensor, missing_ratio=i, complete_traj_ratio=0)
    val_dataset = DatasetWithPlans(val_trajectories_tensor, val_mask, val_checkpoints)
    val_dataloader = DataLoader(val_dataset, batch_size=64, shuffle=True)
    evaluate_model(model, val_dataloader)

Validation Loss: 89.70970082233242
Validation Loss: 56.446406791543204
Validation Loss: 43.39389999637739
Validation Loss: 36.56842054119573
Validation Loss: 32.24403993469876
Validation Loss: 23.07389640588127
